###### Server port ########
server:
  port: 9092  # ${SERVICE_PORT}


###### Spring configs ########
spring:
  application:
    name: agent-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Micro_AgentServiceDB
    username: postgres
    password: 123456789

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update   # şemadaki tablolarimin otomaik olarak güncellenmesi için
    show-sql: true

  zipkin:
    base-url:  http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "user"
    password: "user"

springdoc:
  swagger-ui:
    path: /swagger-ui.html


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5