###### Server port ########
server:
  port: 9091  # ${SERVICE_PORT}


###### Spring configs ########
spring:
 application:
  name: user-profile-service
 datasource:
   url: jdbc:postgresql://localhost:5432/Micro_UserProfileServiceDB
   username: postgres
   password: 123456789
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       hbm2ddl:
         auto: update   # şemadaki tablolarimin otomaik olarak güncellenmesi için
   show-sql: true

#   profiles:
#    active: dev


springdoc:
  swagger-ui:
    path: /swagger-ui.html
