server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${REMOTE_CONFIG_PATH_PROJECT}
          default-label: main
          username: ${REMOTE_USERNAME}
          password: ${REMOTE_TOKEN_PASSWORD}



