@echo off
setx DB_USERNAME "KENDI_KULLANICI_ADINI_YAZ"
setx DB_PASSWORD "KENDI_KULLANICI_PAROLANI_YAZ"
setx DB_URL "KENDI_DB_URL_BILGISINI_YAZ"
setx DB_AUTH_SERVICE_NAME "KENDI_DB_ADINI_YAZ"
setx DB_JPA_DIALECT "KENDI_DB_ADINI_YAZ"
setx SERVICE_PORT 9090

setx DB_USER_PROFILE_SERVICE_NAME "KENDI_DB_ADINI_YAZ"

setx REMOTE_CONFIG_PATH_PROJECT "KENDI_CONFIG_URL_ADRESINI_YAZ"
setx REMOTE_USERNAME "KENDI_REMOTE_ADINI_YAZ"
setx REMOTE_TOKEN_PASSWORD "KENDI_REMOTE_PAROLANI_YAZ"


