@echo off
setx DB_USERNAME "KENDI_KULLANICI_ADINI_YAZ"
setx DB_PASSWORD "KENDI_KULLANICI_PAROLANI_YAZ"
setx DB_URL "KENDI_DB_URL_BILGISINI_YAZ"
setx DB_AUTHSERVICE_NAME "KENDI_DB_ADINI_YAZ"

setx DB_JPA_DIALECT "KENDI_DB_ADINI_YAZ"


