apiVersion: v1
kind: Pod
metadata:
  name: mypodcreate-42
  labels:
    name: docker001-hello
    type: back-end
    app: hello-service
    project-name: mydemo
spec:
  containers:
  - name: docker001-hello
    image: mimaraslan/java-042-devops-hello:v001
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
---
apiVersion: v1
kind: Pod
metadata:
  name: mypodcreate-39
  labels:
    name: mydemo2
    type: back-end
    app: mydemo2-service
    project-name: mydemo2
    team: team-3
    group: abc
spec:
  containers:
  - name: mydemo-hello2
    image: mimaraslan/java-039-hello-docker:v001
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090